# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['-release']},
        ),
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
